[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "media-repo"
version = "0.1.0"
authors = [
  { name="Your Name", email="you@example.com" },
]
description = "A repository for managing media files."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "alembic==1.16.1",
    "amqp==5.3.1",
    "apispec==6.8.2",
    "billiard==4.2.1",
    "blinker==1.9.0",
    "celery==5.5.3",
    "certifi==2025.4.26",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "clmediakit @ git+https://github.com/asarangaram/clmediakit.git@44eae6f34fba6db2584e75953ca71633a348ea0a",
    "cryptography==44.0.2",
    "defusedxml==0.7.1",
    "Flask==3.1.1",
    "Flask-Migrate==4.1.0",
    "Flask-RangeRequest==0.0.2",
    "flask-smorest==0.46.1",
    "Flask-SQLAlchemy==3.1.1",
    "greenlet==3.2.3",
    "hnswlib==0.8.0",
    "httpie==3.2.4",
    "humanize==4.12.3",
    "idna==3.10",
    "imagedominantcolor @ git+https://github.com/asarangaram/imagedominantcolor.git@e188d51758513a4a8f6d740c133c2b4e44b4ce35",
    "ImageHash==4.3.2",
    "iniconfig==2.1.0",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.6",
    "kombu==5.5.4",
    "m3u8==6.0.0",
    "Mako==1.3.10",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "marshmallow==4.0.0",
    "mdurl==0.1.2",
    "msgpack==1.1.0",
    "multidict==6.4.4",
    "numpy==2.2.3",
    "opencv-python==4.12.0.88",
    "packaging==25.0",
    "pillow==11.1.0",
    "pillow_heif==0.22.0",
    "pluggy==1.6.0",
    "prompt_toolkit==3.0.51",
    "pycparser==2.22",
    "Pygments==2.19.1",
    "PySocks==1.7.1",
    "pytest==8.4.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "python-magic==0.4.27",
    "pytz==2025.2",
    "PyWavelets==1.8.0",
    "redis==5.2.1",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rich==14.0.0",
    "scipy==1.15.2",
    "six==1.17.0",
    "SQLAlchemy==2.0.41",
    "SQLAlchemy-Continuum==1.4.2",
    "SQLAlchemy-Utils==0.41.2",
    "tendo==0.3.0",
    "typing_extensions==4.14.0",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "uWSGI==2.0.30",
    "videohash @ git+https://github.com/asarangaram/videohash.git@44e6928d29388839871eb1e0ca39605eb253e245",
    "vine==5.1.0",
    "wcwidth==0.2.13",
    "webargs==8.7.0",
    "Werkzeug==3.1.3",
    "yt-dlp==2025.2.19",
]

[project.urls]
"Homepage" = "https://github.com/your-username/media_repo"
"Bug Tracker" = "https://github.com/your-username/media_repo/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 79

[tool.flake8]
ignore = ["E203", "E501"]